### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by tonydjh** [nstudio/nativescript-videoplayer#102]
Got this error when build, and cant use the plugin

node_modules/nativescript-videoplayer/videoplayer.d.ts(60,12): error TS2503: Cannot find namespace 'android'.
node_modules/nativescript-videoplayer/videoplayer.d.ts(61,8): error TS2304: Cannot find name 'UIView'.

i install the plugin using "tns plugin add nativescript-videoplayer" on root proyect folder, install well then put this lines on  my app.component.ts 
 "import { Video } from 'nativescript-videoplayer';
 registerElement("VideoPlayer", () => Video);"  

and when build got the error, what i miss?

**Comment by xtronoid** [comment]
Yes... this happened also with me... even typing as any it complains

another interesting thing when i jumped from ns3 to ns4, is that sometimes after a dozen of dozen of livesyncs (at least it´s what i identified but its a bit random but a bit rare to simulate), the video silently disappears from view since app start, no video, ONLY by restarting telephone...

gc related?

**Comment by bradmartin** [comment]
4.0.3 published to help with this.
