### ISSUE TITLE
Why MediaPlayer and not ExoPlayer for Android?

### ISSUE THREAD

**Issue by avhetman** [nstudio/nativescript-videoplayer#166]
ExoPlayer is more comparable to the AVPlayer that is used for iOS, especially for streaming video. Why was MediaPlayer chosen and would it be possible to wrap ExoPlayer instead or alongside MediaPlayer as a feature request?

**Comment by rigor789** [comment]
There's already an exoplayer plugin you could try by @NathanaelA 
https://github.com/NathanaelA/nativescript-exoplayer

**Comment by avhetman** [comment]
That package would work for just ExoPlayer, but then the consumer would need to be the one to decide when to use what player. I think the value of this nativescript-videoplayer library is that it does this logic.

**Comment by NathanaelA** [comment]
@avhetman - As the author of the ExoPlayer plugin, I am having a really hard time understanding what you are asking for.   

ExoPlayer actually came from this plugin, so the iOS side of the code base is pretty close to identical as what is in this plugin; but on the Android side it uses ExoPlayer instead of MediaPlayer.   

So everything should be wrapped up; the reason we split it into two separate plugins is because to run ExoPlayer the underlying code is completely different so it made no sense to keep the plugins as the same one as the flow is different...  But what is exposed to you consuming the plugin should be pretty close to the same...

**Comment by avhetman** [comment]
Hi @NathanaelA I really appreciate your clarification. It looks like your plugin is what I am looking for after all. Thank you very much!
