### ISSUE TITLE
iOS app crashes when player loads in nativescript-vue NS7

### ISSUE THREAD

**Issue by mreall** [nstudio/nativescript-videoplayer#174]
The app crashes immediately after loading the page with the nativescript-videoplayer component.

To make sure it wasn't a conflict with some other component, I created a new nativescript-vue project and added the following to the respective files:

**app.js**
``
Vue.registerElement('VideoPlayer', () => require('nativescript-videoplayer').Video);
``

**Home.vue**
```
<template>
  <Page>
    <ActionBar>
      <Label text="Home" />
    </ActionBar>

    <StackLayout>
      <VideoPlayer
        src="https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4"
        height="300"
      />
    </StackLayout>
  </Page>
</template>
```

I ran the test app on the iPhone 8 emulator running iOS 14.

Running `ns info`:
```
Component nativescript has 7.0.8 version and is up to date.
Component @nativescript/core has 7.0.3 version and is up to date.
Component @nativescript/ios has 7.0.0 version and is up to date.
```

package.json dependencies:
```
  "dependencies": {
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-videoplayer": "^5.0.0",
    "nativescript-vue": "~2.8.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "babel-loader": "~8.0.0",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.9.3"
  },
```

[Download the project](https://drive.google.com/file/d/19z-HqJlw1sGt3rgF1YxcI-3_-5G5Faut/view?usp=sharing)

**Comment by bradmartin** [comment]
If you remove the videoplayer does the app launch?

**Comment by mreall** [comment]
Yes, it does.

**Comment by bradmartin** [comment]
ugh... I really don't know :/ without having some error or anything, sorry. Can you open the project in xcode and try to run it there and see if you get anything when the app crashes?

**Comment by mdjamal** [comment]
Seeing the same, when the player loads the app crashes with NS7 Vue, opened the project in Xcode and run in emulator still crashes.

Log from Xcode, hope this helps

2020-09-22 14:27:00.434331+0530 atlasbackpain[13367:719496] CONSOLE LOG: Video isActive: true
2020-09-22 14:27:00.505613+0530 atlasbackpain[13367:720151] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600000df7da0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-09-22 14:27:00.524440+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:00.524618+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:00.524775+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:00.525435+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:00.525599+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:00.525767+0530 atlasbackpain[13367:720151]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:01.436722+0530 atlasbackpain[13367:719496] CONSOLE LOG: Video duration: 18000
2020-09-22 14:27:01.440876+0530 atlasbackpain[13367:719496] CONSOLE LOG: Video isPlaying: true
2020-09-22 14:27:02.732173+0530 atlasbackpain[13367:721148]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:02.732380+0530 atlasbackpain[13367:721148]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:02.732563+0530 atlasbackpain[13367:721148]  AudioObjectRemovePropertyListener: no object with given ID 0
2020-09-22 14:27:02.843949+0530 atlasbackpain[13367:719496] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<NSObject: 0x600000f78ed0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: status
Observed object: <AVPlayerItem: 0x600000f78f60, asset = <AVURLAsset: 0x600000dafa40, URL = https://videodelivery.net/1bbb673c1914f0b6a03e97641504989c/manifest/video.m3u8>>
Change: {
    kind = 1;
}
Context: 0x0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   Foundation                          0x00007fff207d5c40 -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 0
	3   Foundation                          0x00007fff207d6124 NSKeyValueNotifyObserver + 329
	4   Foundation                          0x00007fff207d9858 NSKeyValueDidChange + 439
	5   Foundation                          0x00007fff207d562f NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
	6   AVFCore                             0x00007fff578667b9 __avplayeritem_fpItemNotificationCallback_block_invoke + 2222
	7   libdispatch.dylib                   0x00000001093728ac _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x0000000109373a88 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x0000000109381f23 _dispatch_main_queue_callback_4CF + 1152
	10  CoreFoundation                      0x00007fff203a8276 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x00007fff203a2b06 __CFRunLoopRun + 2685
	12  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
	13  GraphicsServices                    0x00007fff2b773db3 GSEventRunModal + 139
	14  UIKitCore                           0x00007fff24660af3 -[UIApplication _run] + 912
	15  UIKitCore                           0x00007fff24665a04 UIApplicationMain + 101
	16  NativeScript                        0x0000000107e54dcd ffi_call_unix64 + 85
	17  ???                                 0x0000600002643ba0 0x0 + 105553156389792
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<NSObject: 0x600000f78ed0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: status
Observed object: <AVPlayerItem: 0x600000f78f60, asset = <AVURLAsset: 0x600000dafa40, URL = https://videodelivery.net/1bbb673c1914f0b6a03e97641504989c/manifest/video.m3u8>>
Change: {
    kind = 1;
}
Context: 0x0'
terminating with uncaught exception of type NSException
CoreSimulator 732.17 - Device: iPhone 11 (034EEF66-0290-41E6-990E-EA1EE1703C4C) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11

**Comment by bradmartin** [comment]
@mdjamal - that does bc your simulator here shows `iOS 14.0` which could be part of the issue. Granted the plugin will likely need changes to accomodate but that could be the culprit here as the videoplayer was working last week on iOS Simulator for me running iOS 13

**Comment by mdjamal** [comment]
@bradmartin does this mean that videoplayer is not yet production ready for iOS 14, any idea when we will have a fix. As a temporary solution guess have to rollback to NS 6.x and videoplayer 4.x

**Comment by bradmartin** [comment]
I'm not sure, I'd guess it's a simple fix somewhere to change. I'll try to find some time later today or tomorrow to see about patching.

**Comment by mreall** [comment]
Thanks @bradmartin. [One estimate](https://mixpanel.com/trends/#report/ios_14) shows iOS 14 adoption above 25% already, so compatibility is increasingly critical.

**Comment by bradmartin** [comment]
I might have found the issue, but I'm currently without internet working on a hotspot via mobile and it's making dev a little slow and painful 😖 so I'm going to push the fixes up to master.

@mreall could you fork/clone and then `cd src && npm run demo.ios` and see if it works on the iOS 14 simulators you have? @mdjamal you could also try the same if you want to confirm that master contains the fix now.

**Comment by mdjamal** [comment]
@bradmartin I can confirm master branch runs the video player without crash. Now trying to have the master added to dependencies and see if it works with my app

**Comment by mreall** [comment]
The demo worked for me @bradmartin. Thanks for turning this around so quickly.

**Comment by bradmartin** [comment]
I'm going to go ahead and publish as I believe the fix was the issue. Basically, when updating the plugin I forgot to add the webpack transformer to the iOS `extends` native class in the iOS source. So the source. code was not transpiled into ES5 which the runtimes need for native extended classes and it was transpiled into es2017 (per tsconfig settings) and as of now the runtimes do not support es2017 extending native classes which is what the `NativeClass()` decorator does in conjunction with `ts-patch install` running on the files prior to `tsc`. If either of you run into issues with other plugins, you can probably use this one and the blog post on updating plugins to see if you can spot maybe something the plugin author forgot to do 😄

**Comment by bradmartin** [comment]
`5.0.1` published to npm , thanks for the help everyone 💯

**Comment by mdjamal** [comment]
Thanks @bradmartin for the quick fix.

**Comment by mreall** [comment]
Thanks again @bradmartin.  I also confirmed the update is working in my app on iOS 14.
